[project]
name = "agri-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.128.0",
    "greenlet>=3.3.0",
    "sqlalchemy>=2.0.45",
]
